name: Feature request
description: Suggest an idea for fno-flow-prediction
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What you want and why.
    validations:
      required: true
